name: meditreat

services:
  api:
    container_name: meditreat_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - meditreat_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  meditreat_network:
    driver: bridge
