name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v2

      - name: Install UV
        uses: astral-sh/setup-uv@v2

      - name: Setup python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Insall ruff
        run: uv add ruff

      - name: Run ruff
        run: uv ruff ruff check --fix --exit-zero

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Compose Image
        run: |
          docker compose build
          docker compose push
